#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import secrets
import sqlite3
import tempfile
import threading

from flask import Flask, abort, flash, redirect, render_template, request, session

app = Flask(__name__)


class TemporaryDB:
    def __init__(self):
        self.db_file = tempfile.NamedTemporaryFile("x", suffix=".db")
        self.connection = sqlite3.connect(self.db_file.name, check_same_thread=False)
        self.connection.row_factory = sqlite3.Row
        self._lock = threading.Lock()

    def execute(self, sql, parameters=()):
        with self._lock:
            cursor = self.connection.cursor()
            result = cursor.execute(sql, parameters)
            self.connection.commit()
            return result


flag = open("/flag").read().strip() if os.geteuid() == 0 else "pwn.college{fake_flag}"

db = TemporaryDB()
db.execute(
    """CREATE TABLE posts AS SELECT ? AS content, "admin" AS author, FALSE AS published""",
    ["Flag has been relocated to its own table for security."],
)
db.execute(
    """CREATE TABLE users AS SELECT "admin" AS username, ? as password""",
    [secrets.token_hex(32)],
)
db.execute(
    """INSERT INTO users SELECT "guest" as username, ? as password""",
    ["password"],
)
db.execute(
    """INSERT INTO users SELECT "hacker" as username, ? as password""",
    ["1337"],
)

flag_table = "flag_" + secrets.token_hex(8)
db.execute(f"CREATE TABLE {flag_table} (val TEXT NOT NULL)")
db.execute(f"INSERT INTO {flag_table} (val) VALUES (?)", (flag,))


@app.route("/login", methods=["GET", "POST"])
def challenge_login():
    if session.get("username"):
        return redirect("/")

    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            flash("Identity credentials required")
            return redirect("/login")

        query = (
            f"SELECT * FROM users WHERE username = '{username}' AND password = '{password}'"
        )

        try:
            user = db.execute(query).fetchone()
        except sqlite3.Error as error:
            flash(f"Database error: {error}")
            return redirect("/login")

        if not user:
            flash("Access denied: Invalid credentials")
            return redirect("/login")

        session["username"] = user["username"]
        return redirect("/")

    return render_template("login.html")


@app.route("/draft", methods=["POST"])
def challenge_draft():
    username = session.get("username", None)
    if not username:
        abort(403, "Log in first!")

    content = request.form.get("content", "")
    db.execute(
        "INSERT INTO posts (content, author, published) VALUES (?, ?, ?)",
        (content, username, bool(request.form.get("publish"))),
    )
    return redirect("/")


@app.route("/publish", methods=["POST"])
def challenge_publish():
    username = session.get("username", None)
    if not username:
        abort(403, "Log in first!")

    db.execute("UPDATE posts SET published = TRUE WHERE author = ?", [username])
    return redirect("/")


@app.route("/", methods=["GET"])
def challenge_get():
    username = session.get("username")
    if not username:
        return redirect("/login")

    posts = db.execute("SELECT * FROM posts").fetchall()
    return render_template("index.html", username=username, posts=posts)


@app.route("/logout")
def challenge_logout():
    session.clear()
    return redirect("/")


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
