#!/usr/bin/exec-suid --real -- /usr/local/bin/python -I

import subprocess

from flask import Flask, render_template, request

app = Flask(__name__)


@app.route("/", methods=["GET"])
def render_banner():
    text = request.args.get("text")
    if not text:
        text = "Marquee"

    command = f"figlet '{text}'"
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    return render_template(
        "index.html", value=request.args.get("text"), banner=result.stdout + result.stderr
    )


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
