#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import re

from bs4 import BeautifulSoup, NavigableString, Tag
from flask import Flask, render_template, request, url_for

app = Flask(__name__)


@app.context_processor
def relurl():
    return {
        "url_for": lambda endpoint, **values: (
            url_for(endpoint, **values).lstrip("/") or "."
        )
    }


def _is_ignorable_text(node):
    return isinstance(node, NavigableString) and not node.strip()


def _document_nodes(soup):
    nodes = []
    for container in (soup.head, soup.body):
        if container is None:
            continue
        nodes.extend(
            node for node in container.contents if not _is_ignorable_text(node)
        )
    return nodes


_JS_ESCAPE = re.compile(r"\\u\{([0-9a-fA-F]+)\}|\\u([0-9a-fA-F]{4})")


def _decode_js_escapes(text):
    def repl(match):
        try:
            return chr(int(match.group(1) or match.group(2), 16))
        except (ValueError, OverflowError):
            return match.group(0)

    return _JS_ESCAPE.sub(repl, text)


def extract_text(value):
    decoded = _decode_js_escapes(value)
    soup = BeautifulSoup(decoded, "html5lib")
    nodes = _document_nodes(soup)

    if len(nodes) != 1:
        return None

    node = nodes[0]
    if not isinstance(node, NavigableString):
        return None

    return str(node)


@app.route("/", methods=["GET"])
def index():
    msg = request.args.get("msg")
    text = extract_text(msg) if msg else None
    banned = bool(msg and text is None)

    return render_template("index.html", msg=text, banned=banned)


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
