#!/usr/bin/env python

from flask import *
import os

app = Flask(__name__)


@app.after_request
def add_headers(response: Response):
    response.headers["Content-Security-Policy"] = (
        "default-src 'self';base-uri 'none';frame-ancestors 'none';"
    )
    return response


@app.route("/")
def main():
    return render_template("mainpage.html", sequence=request.args.get("sequence"))


app.secret_key = os.urandom(8)
app.config["SERVER_NAME"] = f"pwm.college:80"
app.run("pwm.college", 80)
