#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import re

from flask import Flask, render_template, request

app = Flask(__name__)

FILTERS = [
    (r"<\s*/?\s*script\b", 0),
]


def is_banned(value):
    return any(re.search(pattern, value, flags=flags) for pattern, flags in FILTERS)


@app.route("/", methods=["GET"])
def ephemeral():
    msg = request.args.get("msg")
    banned = bool(msg and is_banned(msg))
    return render_template("ephemeral.html", msg=msg, banned=banned)


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
