#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os

from flask import Flask, render_template, request

app = Flask(__name__)


@app.route("/", methods=["GET"])
def ephemeral():
    return render_template("ephemeral.html", msg=request.args.get("msg"))


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal:80"
app.run("challenge.internal", 80)
