#!/usr/bin/env python

import json
import os
import pty
import select
import signal
import socket
import struct
import threading
import fcntl
import termios

from flask import Flask, render_template
from flask_sock import Sock

app = Flask(__name__)
sock = Sock(app)


@app.route("/")
def index():
    return render_template("index.html")


def serve():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("127.0.0.1", 1337))
    s.listen(1)
    while True:
        conn, _ = s.accept()
        pid = os.fork()
        if pid == 0:
            os.setsid()
            s.close()
            for fd in (0, 1, 2):
                os.dup2(conn.fileno(), fd)
            os.closerange(3, 64)
            os.execvp("/bin/bash", ["/bin/bash", "--noediting", "-i"])
            os._exit(1)
        conn.close()
        os.waitpid(pid, 0)


def set_winsize(fd, rows, cols):
    fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))


@sock.route("/api/pty")
def pty_socket(ws):
    pid, fd = pty.fork()
    if pid == 0:
        for sig in (signal.SIGCHLD, signal.SIGINT, signal.SIGQUIT, signal.SIGTSTP):
            signal.signal(sig, signal.SIG_DFL)
        os.environ["TERM"] = "xterm-256color"
        os.environ["HOME"] = "/home/hacker"
        os.environ["PS1"] = r"\[\e[32m\]hacker\[\e[0m\]:\w\$ "
        os.closerange(3, 64)
        try:
            os.setgroups([1000])
        except OSError:
            pass
        os.setresgid(1000, 1000, 1000)
        os.setresuid(1000, 1000, 1000)
        try:
            os.chdir(os.environ["HOME"])
        except OSError:
            os.chdir("/tmp")
        os.execvp("/bin/bash", ["/bin/bash", "--noprofile", "--norc", "-i"])
        return

    alive = threading.Event()
    alive.set()

    def pty_to_ws():
        while alive.is_set():
            r, _, _ = select.select([fd], [], [], 0.2)
            if fd not in r:
                continue
            try:
                data = os.read(fd, 4096)
            except OSError:
                break
            if not data:
                break
            try:
                ws.send(data.decode("utf-8", "replace"))
            except Exception:
                break
        alive.clear()

    threading.Thread(target=pty_to_ws, daemon=True).start()

    try:
        while alive.is_set():
            msg = ws.receive()
            if msg is None:
                break
            try:
                m = json.loads(msg)
            except (ValueError, TypeError):
                continue
            if m.get("t") == "in":
                os.write(fd, m["d"].encode())
            elif m.get("t") == "resize":
                set_winsize(fd, int(m["rows"]), int(m["cols"]))
    finally:
        alive.clear()
        try:
            os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
        try:
            os.waitpid(pid, 0)
        except OSError:
            pass
        try:
            os.close(fd)
        except OSError:
            pass


threading.Thread(target=serve, daemon=True).start()

app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    threaded=True,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
