worker_processes 1;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events { worker_connections 1024; }

http {
    proxy_cache_path /tmp/cache levels=1:2 keys_zone=main:1m inactive=120s;

    server {
        listen 10.0.13.38:443 ssl;
        server_name proxy.internal;

        ssl_certificate     /etc/ssl/certs/internal.cert.pem;
        ssl_certificate_key /etc/ssl/private/internal.key.pem;

        location / {
            proxy_pass https://challenge.internal:443;

            proxy_set_header Range $http_range;

            proxy_cache          main;
            proxy_cache_key      "$uri$is_args$args";
            proxy_cache_valid    400 416  60s;
            proxy_ignore_headers Cache-Control Expires Set-Cookie;

            add_header X-Cache $upstream_cache_status always;
        }
    }
}
