#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import threading

import psycopg2
import psycopg2.extras
from flask import Flask, render_template, request

app = Flask(__name__)



class Database:
    def __init__(self):
        self.connection = psycopg2.connect(
            host="/run/pgsql/sock", dbname="postgres", user="postgres"
        )
        self.connection.autocommit = True
        self._lock = threading.Lock()

    def execute(self, sql, parameters=None):
        with self._lock:
            cursor = self.connection.cursor(
                cursor_factory=psycopg2.extras.RealDictCursor
            )
            cursor.execute(sql, parameters)
            return cursor


flag = open("/flag").read().strip() if os.geteuid() == 0 else "pwn.college{fake_flag}"

db = Database()
db.execute("DROP TABLE IF EXISTS accounts")
db.execute("CREATE TABLE accounts (name TEXT, age INTEGER, secret TEXT)")
db.execute(
    "INSERT INTO accounts VALUES (%s, %s, %s)", ("guest", 80, "nothing-to-see-here")
)
db.execute("INSERT INTO accounts VALUES (%s, %s, %s)", ("hacker", 67, "hello-hacker"))
db.execute("INSERT INTO accounts VALUES (%s, %s, %s)", ("admin", 69, flag))


@app.route("/", methods=["GET"])
def console():
    value = request.args.get("name")
    if value is None:
        return render_template(
            "console.html", query=None, rows=None, error=None
        )

    sql = f"SELECT name, age FROM accounts WHERE name ILIKE '{value}'"

    rows = None
    error = None
    try:
        rows = db.execute(sql).fetchall()
    except psycopg2.Error as exc:
        error = f"SQL error: {str(exc).strip()}"

    return render_template(
        "console.html", query=sql, value=value, rows=rows, error=error
    )


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
