#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os

from bs4 import BeautifulSoup
from flask import Flask, render_template, request, url_for

app = Flask(__name__)


@app.context_processor
def relurl():
    return {
        "url_for": lambda endpoint, **values: (
            url_for(endpoint, **values).lstrip("/") or "."
        )
    }


ALLOWED_TAGS = {"html", "head", "body", "math", "mtext", "mglyph", "style", "table"}
ALLOWED_ATTRS = {
    "table": {"id"},
}


def sanitize(html):
    soup = BeautifulSoup(html, "html5lib")
    for tag in soup.find_all(True):
        if tag.name not in ALLOWED_TAGS:
            tag.decompose()
            continue
        for attr in list(tag.attrs):
            allowed = ALLOWED_ATTRS.get(tag.name, set())
            if attr.lower() not in allowed:
                del tag.attrs[attr]
    body = soup.body
    return body.decode_contents() if body else ""


@app.route("/", methods=["GET"])
def index():
    msg = request.args.get("msg", "")
    sanitized = sanitize(msg) if msg else ""
    return render_template("index.html", msg=msg, sanitized=sanitized)


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
