#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import secrets
import sqlite3
import tempfile
import threading

from flask import (
    Flask,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    session,
)
from werkzeug.security import check_password_hash, generate_password_hash

app = Flask(__name__)


class TemporaryDB:
    def __init__(self):
        self.db_file = tempfile.NamedTemporaryFile("x", suffix=".db")
        self.connection = sqlite3.connect(self.db_file.name, check_same_thread=False)
        self.connection.row_factory = sqlite3.Row
        self._lock = threading.Lock()

    def execute(self, sql, parameters=()):
        with self._lock:
            cursor = self.connection.cursor()
            result = cursor.execute(sql, parameters)
            self.connection.commit()
            return result


flag = open("/flag").read().strip() if os.geteuid() == 0 else "pwn.college{fake_flag}"

db = TemporaryDB()
db.execute(
    """CREATE TABLE users AS SELECT "admin" AS username, ? as password""",
    [generate_password_hash(flag)],
)
db.execute(
    """INSERT INTO users SELECT "guest" as username, ? as password""",
    [generate_password_hash("password")],
)
db.execute(
    """INSERT INTO users SELECT "hacker" as username, ? as password""",
    [generate_password_hash("1337")],
)
db.execute("""CREATE TABLE posts (content TEXT, author TEXT)""")
for author, content in [
    ("admin", "Welcome to pwnpost!"),
    ("admin", "Reminder: rotate your session tokens regularly."),
    ("guest", "First!"),
    ("guest", "Anyone else McLovin the new redesign?"),
    ("hacker", "pwn.college is pretty cool, innit? 🇬🇧"),
    ("hacker", "Testing 1337 2 3."),
]:
    db.execute(
        "INSERT INTO posts (content, author) VALUES (?, ?)",
        (content, author),
    )


@app.route("/login", methods=["GET", "POST"])
def challenge_login():
    if session.get("username"):
        return redirect("/")

    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            flash("Identity credentials required")
            return redirect("/login")

        user = db.execute(
            "SELECT * FROM users WHERE username = ?",
            (username,),
        ).fetchone()

        if not user or not check_password_hash(user["password"], password):
            flash("Access denied: Invalid credentials")
            return redirect("/login")

        session["username"] = username
        return redirect("/")

    return render_template("login.html")


@app.route("/", methods=["GET"])
def challenge_get():
    username = session.get("username")
    if not username:
        return redirect("/login")

    msg = request.args.get("msg", "")
    token = flag if username == "admin" else "n/a"
    csp_nonce = secrets.token_urlsafe(32)

    if msg:
        posts = db.execute(
            "SELECT * FROM posts WHERE INSTR(content, ?) > 0",
            (msg,),
        ).fetchall()
    else:
        posts = db.execute("SELECT * FROM posts").fetchall()

    response = make_response(
        render_template(
            "index.html",
            username=username,
            msg=msg,
            token=token,
            posts=posts,
            csp_nonce=csp_nonce,
        )
    )
    response.headers["Content-Security-Policy"] = (
        "default-src 'self'; "
        f"script-src 'nonce-{csp_nonce}' https://cdn.internal; "
        "style-src 'self' https://cdn.internal 'unsafe-inline'; "
        "font-src 'self' https://cdn.internal; "
        "img-src 'self' https://cdn.internal"
    )
    return response


@app.route("/logout")
def challenge_logout():
    session.clear()
    return redirect("/")


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.config["SESSION_COOKIE_HTTPONLY"] = False
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
