#!/usr/bin/exec-suid --real --environ=none -- /usr/local/bin/python -I

import atexit
import sys
from urllib.parse import urlparse

from selenium import webdriver
from selenium.common.exceptions import TimeoutException, WebDriverException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        url = sys.argv[1]
    else:
        print("What url should I visit?")
        url = input()

    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        print("Invalid url!!!")
        sys.exit(1)

    if parsed.hostname != "challenge.internal":
        print("Invalid host!!!")
        sys.exit(1)

    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--ignore-certificate-errors")
    options.add_argument("--disable-dev-shm-usage")
    options.binary_location = "/usr/bin/chromium"
    service = Service("/usr/bin/chromedriver")
    driver = None

    try:
        driver = webdriver.Chrome(service=service, options=options)
        atexit.register(driver.quit)

        print(f"Visiting {url}")
        driver.get(url)

        WebDriverWait(driver, 1).until(EC.alert_is_present())
    except WebDriverException:
        print(f"There was an error visiting {url}")
    except TimeoutException:
        print("Failure: JavaScript alert did not trigger...")
    else:
        print(f"You win! Here is your flag: {open('/flag').read().strip()}")
