#!/usr/bin/exec-suid --real --environ=none -- /usr/local/bin/python -I

import atexit
import ctypes
import os
import shutil
import sys
import tempfile
from urllib.parse import urlparse

from selenium import webdriver
from selenium.common.exceptions import TimeoutException, WebDriverException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

NETNS = os.environ.get("NETNS", "challenge_ns")
CLONE_NEWNET = 0x40000000

libc = ctypes.CDLL(ctypes.util.find_library("c"), use_errno=True)

with open(f"/var/run/netns/{NETNS}") as ns:
    if libc.setns(ns.fileno(), CLONE_NEWNET) != 0:
        err = ctypes.get_errno()
        raise OSError(err, os.strerror(err))

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        url = sys.argv[1]
    else:
        print("What url should I visit?")
        url = input()

    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        print("Invalid url!!!")
        exit(1)

    old_umask = os.umask(0o077)
    profile_dir = tempfile.mkdtemp(prefix="chromium-profile-")
    os.umask(old_umask)

    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument(f"--user-data-dir={profile_dir}")
    options.binary_location = "/usr/bin/chromium"
    service = Service("/usr/bin/chromedriver")
    driver = None

    try:
        driver = webdriver.Chrome(service=service, options=options)
        atexit.register(driver.quit)

        print("Setting cookie...")
        driver.get("http://challenge.internal/")
        driver.add_cookie(
            {
                "name": "admin_token",
                "value": open("/challenge/.admin_token").read().strip(),
                "path": "/",
                "httpOnly": True,
            }
        )

        print(f"Visiting {url}")
        driver.get(url)

        WebDriverWait(driver, 1).until(EC.alert_is_present())
    except WebDriverException:
        print(f"There was an error visiting {url}")
    except TimeoutException:
        print("Failure: JavaScript alert did not trigger...")
    else:
        print(f"You win! Here is your flag: {open('/flag').read().strip()}")
    finally:
        if driver is not None:
            driver.quit()
        shutil.rmtree(profile_dir, ignore_errors=True)
