#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import re
import secrets

from flask import Flask, make_response, render_template, request

app = Flask(__name__)

BLOCKLIST = [
    (r"<\s*/?\s*script\b", re.IGNORECASE),
    (r"<\s*/?\s*img\b", re.IGNORECASE),
    (r"<\s*/?\s*svg\b", re.IGNORECASE),
    (r"<\s*/?\s*iframe\b", re.IGNORECASE),
    (r"<\s*/?\s*input\b", re.IGNORECASE),
    (r"<\s*/?\s*video\b", re.IGNORECASE),
    (r"<\s*/?\s*audio\b", re.IGNORECASE),
    (r"<\s*/?\s*source\b", re.IGNORECASE),
    (r"<\s*/?\s*track\b", re.IGNORECASE),
    (r"<\s*/?\s*html\b", re.IGNORECASE),
    (r"<\s*/?\s*body\b", re.IGNORECASE),
    (r"<\s*/?\s*frameset\b", re.IGNORECASE),
    (r"<\s*/?\s*details\b", re.IGNORECASE),
    (r"<\s*/?\s*dialog\b", re.IGNORECASE),
    (r"<\s*/?\s*marquee\b", re.IGNORECASE),
    (r"<\s*/?\s*style\b", re.IGNORECASE),
    (r"<\s*/?\s*link\b", re.IGNORECASE),
    (r"<\s*/?\s*template\b", re.IGNORECASE),
    (r"ontoggle", re.IGNORECASE),
    (r"onstart", re.IGNORECASE),
    (r"onload", re.IGNORECASE),
    (r"onerror", re.IGNORECASE),
    (r"onclick", re.IGNORECASE),
    (r"onfocus", re.IGNORECASE),
    (r"onfocusin", re.IGNORECASE),
    (r"onfocusout", re.IGNORECASE),
    (r"autofocus", re.IGNORECASE),
    (r"onanimationstart", re.IGNORECASE),
    (r"onanimationiteration", re.IGNORECASE),
    (r"onanimationend", re.IGNORECASE),
    (r"onanimationcancel", re.IGNORECASE),
    (r"style\s*=", re.IGNORECASE),
    (r"animation", re.IGNORECASE),
    (r"keyframes", re.IGNORECASE),
    (r"content-?visibility", re.IGNORECASE),
    (r"transition", re.IGNORECASE),
    (r"transform", re.IGNORECASE),
    (r"shadow", re.IGNORECASE),
    (r"slot", re.IGNORECASE),
    (r"fetch", re.IGNORECASE),
    (r"xmlhttprequest", re.IGNORECASE),
    (r"sendbeacon", re.IGNORECASE),
    (r"location", re.IGNORECASE),
    (r"open\s*\(", re.IGNORECASE),
    (r"assign\s*\(", re.IGNORECASE),
    (r"replace\s*\(", re.IGNORECASE),
    (r"pushstate", re.IGNORECASE),
    (r"replacestate", re.IGNORECASE),
    (r"submit", re.IGNORECASE),
    (r"requestsubmit", re.IGNORECASE),
    (r"click", re.IGNORECASE),
    (r"createelement(?:ns)?", re.IGNORECASE),
    (r"(?:adopt|import|clone)node", re.IGNORECASE),
    (r"append(?:child)?", re.IGNORECASE),
    (r"prepend", re.IGNORECASE),
    (r"before", re.IGNORECASE),
    (r"after", re.IGNORECASE),
    (r"insertbefore", re.IGNORECASE),
    (r"insertadjacent(?:html|text|element)", re.IGNORECASE),
    (r"replace(?:children|child|with)", re.IGNORECASE),
    (r"remove(?:child)?", re.IGNORECASE),
    (r"innerhtml", re.IGNORECASE),
    (r"outerhtml", re.IGNORECASE),
    (r"(?:inner|outer)(?:text|html)", re.IGNORECASE),
    (r"textcontent", re.IGNORECASE),
    (r"setattribute(?:ns)?", re.IGNORECASE),
    (r"removeattribute(?:ns)?", re.IGNORECASE),
    (r"toggleattribute", re.IGNORECASE),
    (r"queryselector(?:all)?", re.IGNORECASE),
    (r"getelement(?:sbytagname|sbyclassname|byid|sbyname)", re.IGNORECASE),
    (r"write", re.IGNORECASE),
    (r"writeln", re.IGNORECASE),
    (r"href", re.IGNORECASE),
    (r"src", re.IGNORECASE),
    (r"action", re.IGNORECASE),
    (r"formaction", re.IGNORECASE),
    (r"srcdoc", re.IGNORECASE),
    (r"cookiestore", re.IGNORECASE),
    (r"cookie", re.IGNORECASE),
    (r"(?:local|session)storage", re.IGNORECASE),
    (r"formdata", re.IGNORECASE),
    (r"url(?:searchparams)?", re.IGNORECASE),
    (r"request", re.IGNORECASE),
    (r"headers", re.IGNORECASE),
    (r"response", re.IGNORECASE),
    (r"media", re.IGNORECASE),
    (r"image", re.IGNORECASE),
    (r"audio", re.IGNORECASE),
    (r"video", re.IGNORECASE),
    (r"track", re.IGNORECASE),
    (r"source", re.IGNORECASE),
    (r"bitmap", re.IGNORECASE),
    (r"canvas", re.IGNORECASE),
    (r"blob", re.IGNORECASE),
    (r"file", re.IGNORECASE),
    (r"navigator", re.IGNORECASE),
    (r"postmessage", re.IGNORECASE),
    (r"document", re.IGNORECASE),
    (r"window", re.IGNORECASE),
    (r"globalthis", re.IGNORECASE),
    (r"global", re.IGNORECASE),
    (r"self", re.IGNORECASE),
    (r"this", re.IGNORECASE),
    (r"top", re.IGNORECASE),
    (r"parent", re.IGNORECASE),
    (r"frames", re.IGNORECASE),
    (r"form", re.IGNORECASE),
    (r"element", re.IGNORECASE),
    (r"eval", re.IGNORECASE),
    (r"function", re.IGNORECASE),
    (r"constructor", re.IGNORECASE),
    (r"set(?:timeout|interval)", re.IGNORECASE),
]

STRING_LITERAL = re.compile(r"""(["'`])((?:\\.|(?!\1).)*)\1""", re.DOTALL)


def has_long_string_literal(value):
    for match in STRING_LITERAL.finditer(value):
        if len(match.group(2)) > 1:
            return True
    return False


def is_banned(value):
    return has_long_string_literal(value) or any(
        re.search(pattern, value, flags=flags) for pattern, flags in BLOCKLIST
    )


@app.route("/", methods=["GET"])
def ephemeral():
    msg = request.args.get("msg")
    banned = bool(msg and is_banned(msg))
    csp_nonce = secrets.token_urlsafe(16)

    response = make_response(
        render_template(
            "ephemeral.html",
            msg=msg,
            banned=banned,
            csp_nonce=csp_nonce,
            share_url=request.url if msg else "",
        )
    )
    response.headers["Content-Security-Policy"] = (
        f"style-src 'nonce-{csp_nonce}'; style-src-attr 'none'"
    )
    return response


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
