#!/usr/bin/exec-suid --environ=none --real -- /usr/local/bin/python -I

import shlex
import subprocess

from flask import Flask, render_template, request

app = Flask(__name__)


@app.route("/", methods=["GET"])
def backup():
    target = request.args.get("target")
    if not target:
        return render_template("console.html", output=None)

    args = ["tar", "cf", "/tmp/backup.tar"] + shlex.split(target)
    result = subprocess.run(args, capture_output=True, text=True)
    return render_template(
        "console.html", value=target, output=result.stdout + result.stderr
    )


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
