#!/usr/bin/env python

import os

from flask import Flask, request

app = Flask(__name__)


@app.route("/", methods=["GET"])
def health():
    return "OK\n", 200


@app.route("/execvp")
def execvp():
    cmd = request.args.get("cmd").split(" ")

    return os.execvp(cmd[0], cmd[1:])


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
