#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import sqlite3
import tempfile
import threading

from flask import Flask, render_template, request

app = Flask(__name__)



class TemporaryDB:
    def __init__(self):
        self.db_file = tempfile.NamedTemporaryFile("x", suffix=".db")
        self.connection = sqlite3.connect(self.db_file.name, check_same_thread=False)
        self.connection.row_factory = sqlite3.Row
        self._lock = threading.Lock()

    def execute(self, sql, parameters=()):
        with self._lock:
            cursor = self.connection.cursor()
            result = cursor.execute(sql, parameters)
            self.connection.commit()
            return result


flag = open("/flag").read().strip() if os.geteuid() == 0 else "pwn.college{fake_flag}"

db = TemporaryDB()
db.execute("CREATE TABLE users (username TEXT, role TEXT, secret TEXT)")
db.execute("INSERT INTO users VALUES ('guest', 'reader', 'nothing-to-see-here')")
db.execute("INSERT INTO users VALUES ('hacker', 'hacker', 'hacking')")
db.execute("INSERT INTO users VALUES ('admin', 'superuser', ?)", [flag])


@app.route("/", methods=["GET"])
def console():
    value = request.args.get("username")
    if value is None:
        return render_template(
            "console.html", query=None, rows=None, error=None
        )

    sql = f"SELECT username, role FROM users WHERE username LIKE '{value}'"

    rows = None
    error = None
    try:
        rows = db.execute(sql).fetchall()
    except sqlite3.Error as exc:
        error = f"SQL error: {exc}"

    return render_template(
        "console.html", query=sql, value=value, rows=rows, error=error
    )


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
