#!/usr/bin/env python

import gzip
import io
import os

from flask import Flask, request

app = Flask(__name__)
app.config["SERVER_NAME"] = "challenge.internal"
app.config["MAX_CONTENT_LENGTH"] = 2 * 1024 * 1024  # 2 MB compressed cap

MAX_DECOMPRESSED = 1 * 1024 * 1024 * 1024  # 1 GB
CHUNK = 64 * 1024


@app.get("/health")
def health():
    return "OK\n", 200


@app.post("/upload")
def upload():
    raw = request.get_data()
    try:
        decompressor = gzip.GzipFile(fileobj=io.BytesIO(raw))
    except OSError:
        return {"error": "Invalid gzip"}, 400

    total = 0
    try:
        while True:
            chunk = decompressor.read(CHUNK)
            if not chunk:
                break
            total += len(chunk)
            if total > MAX_DECOMPRESSED:
                os._exit(137)
    except OSError:
        return {"error": "Invalid gzip"}, 400

    return {"size": total}


app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
