#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import sqlite3
import tempfile
import threading

from flask import Flask, render_template, request

app = Flask(__name__)


class TemporaryDB:
    def __init__(self):
        self.db_file = tempfile.NamedTemporaryFile("x", suffix=".db")
        self.connection = sqlite3.connect(self.db_file.name, check_same_thread=False)
        self.connection.row_factory = sqlite3.Row
        self._lock = threading.Lock()

    def execute(self, sql, parameters=()):
        with self._lock:
            cursor = self.connection.cursor()
            result = cursor.execute(sql, parameters)
            self.connection.commit()
            return result


flag = open("/flag").read().strip() if os.geteuid() == 0 else "pwn.college{fake_flag}"

db = TemporaryDB()
db.execute("CREATE TABLE users (username TEXT, password TEXT)")
db.execute("INSERT INTO users VALUES ('guest', 'password')")
db.execute("INSERT INTO users VALUES ('hacker', '1337')")
db.execute("INSERT INTO users VALUES ('admin', ?)", [os.urandom(16).hex()])


@app.route("/", methods=["GET"])
def login():
    username = request.args.get("username")
    password = request.args.get("password")
    if username is None or password is None:
        return render_template("login.html", query=None, attempted=False)

    sql = f"SELECT username FROM users WHERE username = '{username}' AND password = '{password}'"

    user = None
    error = None
    try:
        authenticated = db.execute(sql).fetchone() is not None
        user = username if authenticated else None
    except sqlite3.Error as exc:
        error = f"SQL error: {exc}"

    return render_template(
        "login.html",
        query=sql,
        username_value=username,
        password_value=password,
        attempted=True,
        user=user,
        flag=flag if user == "admin" else None,
        error=error,
    )


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
