#!/usr/bin/env python

import urllib.parse

from flask import Flask, request

app = Flask(__name__)


@app.route("/", methods=["GET"])
def smuggle():
    raw_qs = request.query_string.decode("latin-1")
    if not raw_qs.startswith("payload="):
        return "Missing payload.\n", 400

    payload = urllib.parse.unquote_to_bytes(raw_qs[len("payload=") :])
    target = b"user=hacker&flag=true=1"
    if payload != target:
        return "Wrong bytes.\n", 400

    with open("/flag", "r") as f:
        return f.read()


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
