#!/usr/bin/exec-suid --real --environ=none -- /usr/local/bin/python -I

import hashlib
import html
import os
import shutil
import sqlite3
import tempfile
import threading

from flask import Flask, abort, redirect, request
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

app = Flask(__name__)


flag = open("/flag").read().strip() if os.geteuid() == 0 else "pwn.college{fake_flag}"


class TemporaryDB:
    def __init__(self):
        self.db_file = tempfile.NamedTemporaryFile("x", suffix=".db")
        self.connection = sqlite3.connect(self.db_file.name, check_same_thread=False)
        self.connection.row_factory = sqlite3.Row
        self._lock = threading.Lock()

    def execute(self, sql, parameters=()):
        with self._lock:
            cursor = self.connection.cursor()
            result = cursor.execute(sql, parameters)
            self.connection.commit()
            return result


db = TemporaryDB()

# https://www.sqlite.org/lang_createtable.html
db.execute(
    """CREATE TABLE posts AS SELECT ? AS content, "admin" AS author, FALSE AS published""",
    [flag],
)
db.execute(
    """CREATE TABLE users AS SELECT "admin" AS username, ? as password""", [flag[-20:]]
)
# https://www.sqlite.org/lang_insert.html
db.execute("""INSERT INTO users SELECT "guest" as username, "password" as password""")
db.execute("""INSERT INTO users SELECT "hacker" as username, "1337" as password""")


@app.route("/login", methods=["POST"])
def challenge_login():
    username = request.form.get("username")
    password = request.form.get("password")
    if not username:
        abort(400, "Missing `username` form parameter")
    if not password:
        abort(400, "Missing `password` form parameter")

    # https://www.sqlite.org/lang_select.html
    user = db.execute(
        "SELECT * FROM users WHERE username = ? AND password = ?", (username, password)
    ).fetchone()
    if not user:
        abort(403, "Invalid username or password")

    response = redirect("/")
    response.set_cookie("auth", username + "|" + password)
    return response


@app.route("/draft", methods=["POST"])
def challenge_draft():
    username, password = request.cookies.get("auth", "|").split("|")
    user = db.execute(
        "SELECT * FROM users WHERE username = ? AND password = ?", (username, password)
    ).fetchone()
    if not user:
        abort(403, "Invalid username or password")

    if username == "admin":
        abort(
            400,
            "pwnpost no longer supports admin posting due to rampant flag disclosure",
        )
    content = request.form.get("content", "")
    # https://www.sqlite.org/lang_insert.html
    db.execute(
        "INSERT INTO posts (content, author, published) VALUES (?, ?, ?)",
        (content, username, bool(request.form.get("publish"))),
    )
    return redirect("/")


@app.route("/publish", methods=["POST"])
def challenge_publish():
    username, password = request.cookies.get("auth", "|").split("|")
    user = db.execute(
        "SELECT * FROM users WHERE username = ? AND password = ?", (username, password)
    ).fetchone()
    if not user:
        abort(403, "Invalid username or password")

    if username == "admin":
        abort(
            400,
            "pwnpost no longer supports admin posting due to rampant flag disclosure",
        )
    # https://www.sqlite.org/lang_update.html
    db.execute("UPDATE posts SET published = TRUE WHERE author = ?", [username])
    return redirect("/")


@app.route("/victim", methods=["GET", "POST"])
def victim():
    if request.method == "GET":
        return """
            <html><body>
            <h1>Victim</h1>
            <form action="/victim" method="post">
              URL:<input type="text" name="url" placeholder="http://challenge.localhost/" size="50">
              <input type="submit" value="Visit">
            </form>
            </body></html>
        """

    url = request.form.get("url", "").strip()
    if not url:
        abort(400, "Missing `url` form parameter")

    old_umask = os.umask(0o077)
    profile_dir = tempfile.mkdtemp(prefix="chromium-profile-")
    os.umask(old_umask)

    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument(f"--user-data-dir={profile_dir}")
    options.binary_location = "/usr/bin/chromium"
    service = Service("/usr/bin/chromedriver")
    driver = None

    try:
        driver = webdriver.Chrome(service=service, options=options)
        driver.get("http://challenge.localhost/")
        driver.add_cookie(
            {
                "name": "token",
                "value": flag,
                "path": "/",
            }
        )

        driver.get(url)
        driver.implicitly_wait(5)
    finally:
        if driver is not None:
            driver.quit()
        shutil.rmtree(profile_dir, ignore_errors=True)

    return f"""
        <html><body>
        Victim visited the site: {html.escape(url)}
        <br><a href="/victim">Back</a>
        </body></html>
    """


@app.route("/", methods=["GET"])
def challenge_get():
    page = "<html><body>\nWelcome to pwnpost, now with users!<hr>\n"
    username, password = request.cookies.get("auth", "|").split("|")
    user = db.execute(
        "SELECT * FROM users WHERE username = ? AND password = ?", (username, password)
    ).fetchone()
    if user:
        page += """
            <form action=draft method=post>
              Post:<textarea name=content>Write something!</textarea>
              <input type=checkbox name=publish>Publish
              <input type=submit value=Save>
            </form><br>
            <form action=publish method=post><input type=submit value="Publish All Drafts"></form>
            <hr>
        """

        for post in db.execute("SELECT * FROM posts").fetchall():
            page += f"""<h2>Author: {post["author"]}</h2>"""
            if post["published"]:
                page += post["content"] + "<hr>\n"
            elif post["author"] == username:
                page += "<b>YOUR DRAFT POST:</b> " + post["content"] + "<hr>\n"
            else:
                page += f"""(Draft post, showing first 12 characters):<br>{post["content"][:12]}<hr>"""
    else:
        page += """
            <form action=login method=post>
              Username:<input type=text name=username>
              Password:<input type=text name=password>
              <input type=submit name=submit value=Login>
            </form><hr>
        """

    return page + "</body></html>"


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.localhost:80"
app.run("challenge.localhost", 80)
