#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import ctypes
import ctypes.util
import logging
import os
import sqlite3
import tempfile
import threading

from flask import Flask, abort, flash, redirect, render_template, request, session
from werkzeug.security import check_password_hash, generate_password_hash

app = Flask(__name__)

NETNS = os.environ.get("NETNS", "challenge_ns")
CLONE_NEWNET = 0x40000000

libc = ctypes.CDLL(ctypes.util.find_library("c"), use_errno=True)

with open(f"/var/run/netns/{NETNS}") as ns:
    if libc.setns(ns.fileno(), CLONE_NEWNET) != 0:
        err = ctypes.get_errno()
        raise OSError(err, os.strerror(err))

if os.getuid() != 0:
    logging.getLogger("werkzeug").disabled = True
    app.logger.disabled = True


class TemporaryDB:
    def __init__(self):
        self.db_file = tempfile.NamedTemporaryFile("x", suffix=".db")
        self.connection = sqlite3.connect(self.db_file.name, check_same_thread=False)
        self.connection.row_factory = sqlite3.Row
        self._lock = threading.Lock()

    def execute(self, sql, parameters=()):
        with self._lock:
            cursor = self.connection.cursor()
            result = cursor.execute(sql, parameters)
            self.connection.commit()
            return result


flag = open("/flag").read().strip() if os.geteuid() == 0 else "pwn.college{fake_flag}"

db = TemporaryDB()
db.execute(
    """CREATE TABLE posts (content TEXT NOT NULL, author TEXT NOT NULL, published BOOLEAN NOT NULL)"""
)
db.execute(
    """CREATE TABLE users AS SELECT "admin" AS username, ? as password""",
    [generate_password_hash(flag)],
)
# https://www.sqlite.org/lang_insert.html
db.execute(
    """INSERT INTO users SELECT "guest" as username, ? as password""",
    [generate_password_hash("password")],
)
db.execute(
    """INSERT INTO users SELECT "hacker" as username, ? as password""",
    [generate_password_hash("1337")],
)


@app.route("/login", methods=["GET", "POST"])
def challenge_login():
    if session.get("username"):
        return redirect("/")

    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            flash("Identity credentials required")
            return redirect("/login")

        # https://www.sqlite.org/lang_select.html
        user = db.execute(
            "SELECT * FROM users WHERE username = ?",
            (username,),
        ).fetchone()

        if not user or not check_password_hash(user["password"], password):
            flash("Access denied: Invalid credentials")
            return redirect("/login")

        session["username"] = username
        return redirect("/")

    return render_template("login.html", hide_chrome=True)


@app.route("/register", methods=["GET", "POST"])
def challenge_register():
    if session.get("username"):
        return redirect("/")

    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            flash("Identity credentials required")
            return redirect("/register")

        user = db.execute(
            "SELECT * FROM users WHERE username = ?",
            (username,),
        ).fetchone()

        if user:
            flash("Username already taken")
            return redirect("/register")

        db.execute(
            "INSERT INTO users (username, password) VALUES (?, ?)",
            (username, generate_password_hash(password)),
        )

        flash("Account created! Please log in.")
        return redirect("/login")

    return render_template("register.html", hide_chrome=True)


@app.route("/draft", methods=["POST"])
def challenge_draft():
    username = session.get("username", None)
    if not username:
        abort(403, "Log in first!")

    if username == "admin":
        abort(
            400,
            "pwnpost doesn't support admin posting",
        )

    content = request.form.get("content", "")
    # https://www.sqlite.org/lang_insert.html
    db.execute(
        "INSERT INTO posts (content, author, published) VALUES (?, ?, ?)",
        (content, username, bool(request.form.get("publish"))),
    )
    return redirect("/")


@app.route("/publish", methods=["POST"])
def challenge_publish():
    username = session.get("username", None)
    if not username:
        abort(403, "Log in first!")

    if username == "admin":
        abort(
            400,
            "pwnpost doesn't support admin posting",
        )

    # https://www.sqlite.org/lang_update.html
    post_id = request.form.get("post_id")
    if post_id:
        db.execute(
            "UPDATE posts SET published = TRUE WHERE author = ? AND rowid = ?",
            [username, post_id],
        )
    else:
        db.execute("UPDATE posts SET published = TRUE WHERE author = ?", [username])
    return redirect("/")


@app.route("/", methods=["GET"])
def challenge_get():
    username = session.get("username")
    if not username:
        return redirect("/login")

    posts = db.execute("SELECT rowid, * FROM posts").fetchall()
    return render_template("index.html", username=username, posts=posts)


@app.route("/logout")
def challenge_logout():
    session.clear()
    return redirect("/")


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.config["SESSION_COOKIE_HTTPONLY"] = False
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
