#!/usr/bin/exec-suid -- /usr/local/bin/python -I

from flask import Flask, render_template, request

app = Flask(__name__)


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/flag")
def flag():
    if request.args.get("key") != "REPLACE_ME":
        return {"error": "Wrong key."}

    with open("/flag") as handle:
        return {"flag": handle.read().strip()}


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
