#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os

from flask import Flask, render_template, request, url_for

app = Flask(__name__)


@app.context_processor
def relurl():
    return {
        "url_for": lambda endpoint, **values: (
            url_for(endpoint, **values).lstrip("/") or "."
        )
    }


@app.after_request
def apply_csp(response):
    response.headers["Content-Security-Policy"] = (
        "default-src 'self'; "
        "script-src 'self' http: https:; "
        "style-src 'self' https://cdn.internal 'unsafe-inline'; "
        "font-src 'self' https://cdn.internal; "
        "img-src 'self' data: http: https:; "
        "connect-src *; "
        "object-src 'none'; "
        "base-uri 'none'"
    )
    return response


@app.route("/", methods=["GET"])
def index():
    return render_template("index.html", msg=request.args.get("msg"))


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
