#!/usr/bin/exec-suid -- /usr/local/bin/python -I

import os

from flask import Flask, render_template, request

os.chdir("/challenge")

app = Flask(__name__)

BASE = "."


@app.route("/")
def index():
    return render_template("index.html", root=os.getcwd())


@app.route("/api/files")
def files():
    return {"files": sorted(n for n in os.listdir(BASE) if n.endswith(".txt"))}


@app.route("/api/file")
def file():
    name = request.args.get("path")
    if not name:
        return {"error": "No file named."}

    path = f"{BASE}/{name}"
    try:
        with open(path) as handle:
            return {"content": handle.read()}
    except OSError as error:
        return {"error": str(error)}


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
