#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import re
import secrets

from flask import Flask, make_response, render_template, request

app = Flask(__name__)

FILTERS = [
    (r"<\s*/?\s*script\b", re.IGNORECASE),
    (r"<\s*/?\s*img\b", re.IGNORECASE),
    (r"<\s*/?\s*svg\b", re.IGNORECASE),
    (r"<\s*/?\s*iframe\b", re.IGNORECASE),
    (r"<\s*/?\s*input\b", re.IGNORECASE),
    (r"<\s*/?\s*video\b", re.IGNORECASE),
    (r"<\s*/?\s*audio\b", re.IGNORECASE),
    (r"<\s*/?\s*source\b", re.IGNORECASE),
    (r"<\s*/?\s*track\b", re.IGNORECASE),
    (r"<\s*/?\s*html\b", re.IGNORECASE),
    (r"<\s*/?\s*body\b", re.IGNORECASE),
    (r"<\s*/?\s*frameset\b", re.IGNORECASE),
    (r"<\s*/?\s*details\b", re.IGNORECASE),
    (r"<\s*/?\s*dialog\b", re.IGNORECASE),
    (r"<\s*/?\s*marquee\b", re.IGNORECASE),
    (r"<\s*/?\s*style\b", re.IGNORECASE),
    (r"<\s*/?\s*link\b", re.IGNORECASE),
    (r"<\s*/?\s*template\b", re.IGNORECASE),
    (r"\bontoggle\b", re.IGNORECASE),
    (r"\bonstart\b", re.IGNORECASE),
    (r"\bonload\b", re.IGNORECASE),
    (r"\bonerror\b", re.IGNORECASE),
    (r"\bonclick\b", re.IGNORECASE),
    (r"\bonfocus\b", re.IGNORECASE),
    (r"\bonfocusin\b", re.IGNORECASE),
    (r"\bonfocusout\b", re.IGNORECASE),
    (r"\bautofocus\b", re.IGNORECASE),
    (r"\bonanimationstart\b", re.IGNORECASE),
    (r"\bonanimationiteration\b", re.IGNORECASE),
    (r"\bonanimationend\b", re.IGNORECASE),
    (r"\bonanimationcancel\b", re.IGNORECASE),
    (r"\bstyle\s*=", re.IGNORECASE),
    (r"\banimation\b", re.IGNORECASE),
    (r"\bkeyframes\b", re.IGNORECASE),
    (r"\bcontent-visibility\b", re.IGNORECASE),
    (r"\bcontentvisibility\b", re.IGNORECASE),
    (r"\btransition\b", re.IGNORECASE),
    (r"\btransform\b", re.IGNORECASE),
    (r"shadow", re.IGNORECASE),
    (r"slot", re.IGNORECASE),
]


def is_banned(value):
    return any(re.search(pattern, value, flags=flags) for pattern, flags in FILTERS)


@app.route("/", methods=["GET"])
def ephemeral():
    msg = request.args.get("msg")
    banned = bool(msg and is_banned(msg))
    csp_nonce = secrets.token_urlsafe(16)

    response = make_response(
        render_template(
            "ephemeral.html",
            msg=msg,
            banned=banned,
            csp_nonce=csp_nonce,
            share_url=request.url if msg else "",
        )
    )
    response.headers["Content-Security-Policy"] = (
        f"style-src 'nonce-{csp_nonce}'; style-src-attr 'none'"
    )

    return response


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
