#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os
import re

from flask import Flask, render_template, request, url_for

app = Flask(__name__)


@app.context_processor
def relurl():
    return {
        "url_for": lambda endpoint, **values: (
            url_for(endpoint, **values).lstrip("/") or "."
        )
    }


BLOCKLIST = [
    (r"<\s*/?\s*script\b", re.IGNORECASE),
    (r"<\s*/?\s*img\b", re.IGNORECASE),
    (r"\bon\w+\s*=", re.IGNORECASE),
]


def is_banned(value):
    return any(re.search(pattern, value, flags=flags) for pattern, flags in BLOCKLIST)


@app.route("/", methods=["GET"])
def index():
    msg = request.args.get("msg")
    banned = bool(msg and is_banned(msg))
    return render_template("index.html", msg=msg, banned=banned)


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
