#!/usr/bin/exec-suid -- /usr/local/bin/python -I

import uuid

from flask import Flask, render_template, request

app = Flask(__name__)

KEY = str(uuid.uuid4())


@app.route("/")
def index():
    flag = None
    if request.args.get("key") == KEY:
        with open("/flag") as handle:
            flag = handle.read().strip()

    return render_template("index.html", key=KEY, flag=flag)


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
