#!/usr/local/bin/python -I

import requests
from flask import Flask, Response, request

app = Flask(__name__)

UPSTREAM_URL = "http://localhost:1337"

# RFC 7230
EXCLUDE_HEADERS = [
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailers",
    "transfer-encoding",
    "upgrade",
]


def filter_headers(headers):
    return {
        name: value
        for name, value in headers.items()
        if name.lower() not in EXCLUDE_HEADERS
    }


@app.route(
    "/",
    defaults={"path": ""},
    methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD"],
)
@app.route(
    "/<path:path>", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD"]
)
def proxy(path):
    upstream = f"{UPSTREAM_URL}/{path}"
    headers = filter_headers(request.headers)
    original_for = request.headers.get("X-Forwarded-For")
    client_ip = request.remote_addr or ""
    headers["X-Forwarded-For"] = (
        f"{original_for + ', ' if original_for else ''}{client_ip}"
    )
    headers["X-Forwarded-Host"] = request.headers.get("Host", "")
    headers["X-Forwarded-Proto"] = request.scheme

    resp = requests.request(
        method=request.method,
        url=upstream,
        headers=headers,
        params=request.args,
        data=request.get_data(),
        cookies=request.cookies,
        allow_redirects=False,
        stream=True,
    )

    response_headers = filter_headers(resp.headers)

    return Response(resp.raw, status=resp.status_code, headers=response_headers)


if __name__ == "__main__":
    app.run(host="challenge.localhost", port=80)
