#!/usr/bin/exec-suid --real --environ=none -- /usr/local/bin/python -I

import atexit
import os
import sys
import time

import psutil
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.firefox.service import Service as FirefoxService

if __name__ == "__main__":
    service = FirefoxService(
        executable_path="/usr/local/bin/geckodriver", log_path="/dev/null"
    )
    options = FirefoxOptions()
    options.add_argument("--headless")
    options.binary_location = "/usr/bin/firefox"
    browser = webdriver.Firefox(service=service, options=options)
    atexit.register(browser.quit)

    # Wait for service to start
    for i in range(5):
        open_ports = {
            s.laddr.port
            for s in psutil.net_connections(kind="inet")
            if s.status == "LISTEN"
        }
        if 80 in open_ports:
            break
        time.sleep(1)
    else:
        print("Service doesn't seem to be running?")
        sys.exit(1)

    challenge_url = "http://challenge.localhost:80/register"
    flag = open("/flag").read().strip()

    print(f"Visiting {challenge_url}")
    browser.get(challenge_url)

    print("Registering an account...")
    browser.find_element(By.NAME, "username").send_keys(os.urandom(32).hex())
    browser.find_element(By.NAME, "password").send_keys(flag)
    browser.find_element(By.NAME, "submit").submit()

    time.sleep(3)
    print("Registered!")
