#!/usr/bin/exec-suid -- /usr/local/bin/python3 -I

import psutil
import atexit
import time
import sys
import os
import re

from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, WebDriverException, StaleElementReferenceException

from urllib.parse import quote_plus

os.setuid(os.geteuid())
os.environ.clear()
os.environ["PATH"] = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

options = FirefoxOptions()
options.add_argument("--headless")
service = FirefoxService(executable_path="/usr/local/bin/geckodriver", log_path="/dev/null")
browser = webdriver.Firefox(service=service, options=options)
atexit.register(browser.quit)

open_ports = {s.laddr.port for s in psutil.net_connections(kind="inet") if s.status == "LISTEN"}
if 80 not in open_ports:
    print("Service doesn't seem to be running?")
    sys.exit(1)

URL = "http://challenge.localhost:80/"

if len(sys.argv) >= 2:
    message = sys.argv[1]
else:
    print("What message should I see?")
    message = input()

browser.get(URL)
browser.add_cookie({"name":"secret","value":open("/flag").read()})

challenge_url = f"{URL}?username=admin&message={quote_plus(message)}"
print(f"Visiting {challenge_url}")
browser.get(challenge_url)
browser.implicitly_wait(2)