#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os

from bs4 import BeautifulSoup
from flask import Flask, render_template, request

app = Flask(__name__)

ALLOWED_TAGS = {"html", "head", "body", "math", "mtext", "annotation-xml", "style", "table"}
ALLOWED_ATTRS = {
    "annotation-xml": {"encoding"},
}


def sanitize(html):
    soup = BeautifulSoup(html, "html5lib")
    for tag in soup.find_all(True):
        if tag.name not in ALLOWED_TAGS:
            tag.decompose()
            continue
        for attr in list(tag.attrs):
            allowed = ALLOWED_ATTRS.get(tag.name, set())
            if attr.lower() not in allowed:
                del tag.attrs[attr]
    body = soup.body
    return body.decode_contents() if body else ""


@app.route("/", methods=["GET"])
def ephemeral():
    msg = request.args.get("msg", "")
    sanitized = sanitize(msg) if msg else ""
    return render_template("ephemeral.html", msg=msg, sanitized=sanitized)


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
