#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os

from flask import Flask, render_template, url_for

app = Flask(__name__)


@app.context_processor
def relurl():
    return {
        "url_for": lambda endpoint, **values: (
            url_for(endpoint, **values).lstrip("/") or "."
        )
    }


@app.route("/", methods=["GET"])
def index():
    return render_template("index.html")


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
