#!/usr/bin/exec-suid --environ=none -- /usr/local/bin/python -I

import os

import flask

app = flask.Flask(__name__)


@app.route("/", methods=["GET"])
def index():
    return flask.render_template("sender.html")


app.secret_key = os.urandom(64)
app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
