#!/usr/bin/exec-suid --real --environ=none -- /usr/local/bin/python -I

import atexit
import os
import sys
import time

import psutil
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.firefox.service import Service as FirefoxService

from urllib.parse import quote_plus

service = FirefoxService(
    executable_path="/usr/local/bin/geckodriver", log_path="/dev/null"
)
options = FirefoxOptions()
options.add_argument("--headless")
options.binary_location = "/usr/bin/firefox"
browser = webdriver.Firefox(service=service, options=options)
atexit.register(browser.quit)

def parse_role(role):
    if role in ("admin_noflag","user_flag","user_noflag"):
        return role
    elif role == "admin_flag":
        print("Can't request the flag; not setting role")
        return None
    else:
        print("Unrecognized role; not setting role")
        return None

if len(sys.argv) >= 3:
    message = sys.argv[1]
    role = parse_role(sys.argv[2])
else:
    print("What message should I see?")
    message = input()
    print("What role should I use?")
    role = parse_role(input())



challenge_url = "http://pwm.college:80/"
flag = open("/flag").read().strip()

print(f"Visiting {challenge_url}")
browser.get(challenge_url)

print("Setting cookie...")
browser.add_cookie({"name": "secret", "value": open("/challenge/secret").read()})

if role is not None:
    message_url = f"{challenge_url}?role={role}&message={quote_plus(message)}"
else:
    message_url = f"{challenge_url}?message={quote_plus(message)}"
print(f"Visiting {message_url}")
browser.get(message_url)

time.sleep(2)
print("Visited!")
