#!/usr/bin/exec-suid -- /usr/local/bin/python -I

import os

from flask import Flask, render_template, request

os.chdir("/challenge")

app = Flask(__name__)

BASE = "."


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/fortunes")
def fortunes():
    return {"fortunes": sorted(n for n in os.listdir(BASE) if n.endswith(".txt"))}


@app.route("/api/fortune")
def fortune():
    name = request.args.get("name")
    if not name:
        return {"error": "No fortune named."}

    if ".." in name:
        return {"error": "Path traversal is not allowed."}

    path = os.path.join(BASE, name)
    try:
        with open(path) as handle:
            return {"content": handle.read()}
    except OSError as error:
        return {"error": str(error)}


app.config["SERVER_NAME"] = "challenge.internal"
app.run(
    "challenge.internal",
    443,
    ssl_context=(
        "/etc/ssl/certs/internal.cert.pem",
        "/etc/ssl/private/internal.key.pem",
    ),
)
